# Generated by Django 4.0.4 on 2022-06-07 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supportdesk.basemodel')),
                ('summary', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('is_high_priority', models.BooleanField(default=False)),
                ('status', models.SlugField(choices=[('in-progress', 'In Progress'), ('completed', 'Completed')], default='in-progress', max_length=16)),
                ('completed_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('assigned_to', models.ForeignKey(default=None, limit_choices_to={'user_type': 'agent'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(limit_choices_to={'user_type': 'customer'}, on_delete=django.db.models.deletion.PROTECT, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-status', '-created_on'],
            },
            bases=('supportdesk.basemodel',),
        ),
    ]
